
- id: "${cldds}_bra1"
  desc: "A more efficient set of commands"
  code:
  - diffeoplan.library.DDSCompositeActions
  - id_dds: "${cldds}"
    label: "${cldds}_bra"
    actions:
    - plan: ['F'] # forward
    - plan: ['f'] # backward
    - plan: ['L','R','l','r'] # bracket 1
    - plan: ['R','L','r','l'] # bracket 2
    - plan: ['F', 'l']
    - plan: ['F', 'r']

- id: "${cldds}_addbra1"
  desc: "Simply adding brackets to the commands"
  code:
  - diffeoplan.library.DDSCompositeActions
  - id_dds: "${cldds}"
    label: "${cldds}_bra1"
    actions:
    # maintain all others
    - plan: [0] 
    - plan: [1] 
    - plan: [2] 
    - plan: [3] 
    - plan: [4] 
    - plan: [5] 
    - plan: ['L','R','l','r'] # bracket 1
    - plan: ['R','L','r','l'] # bracket 2
    

- id: "${cldds}_addbra2"
  desc: "Simply adding brackets to the commands"
  code:
  - diffeoplan.library.DDSCompositeActions
  - id_dds: "${cldds}"
    label: "${cldds}_bra2"
    actions:
    # maintain all others
    - plan: [0] 
    - plan: [1] 
    - plan: [2] 
    - plan: [3] 
    - plan: [4] 
    - plan: [5] 
    - plan: ['L','R','l','r'] # bracket [R, L]
    - plan: ['R','L','r','l'] # bracket [L, R]
    - plan: ['L','F','l','f'] # bracket [F, L]
    - plan: ['F','L','f','l'] # bracket [L, F]
    - plan: ['F','R','f','r'] # bracket [R, F]
    - plan: ['R','F','r','f'] # bracket [F, R]


