

- id: "X${lvel}_R${avel}"
  desc: "Forward at .${lvel} units/s and right at ${avel} deg/s."
  code: 
  - diffeoplan.library.MotionDiffeo
  - interval: 1
    avel: "${avel}"
    lvel: ["${lvel}", 0.0]
    topology: plane
 