- id: graphsearch_dir2
  desc: An algorithm that searches all possible sequences of (3 step).
  code:
  - diffeoplan.library.GraphSearchBreadth
  - nsteps: 3
    thresh: 0.1
    metric: neigh2
    directions: 2

- id: graphsearch_breadth_3
  desc: An algorithm that searches all possible sequences of (3 step).
  code:
  - diffeoplan.library.GraphSearchBreadth
  - nsteps: 3
    thresh: 0.1
    metric: neigh2
    
- id: graphsearch_deep_3
  desc: An algorithm that searches all possible sequences of 3 steps.
  code:
  - diffeoplan.library.GraphSearchDeep
  - nsteps: 3
    thresh: 0.1
    metric: neigh2

- id: informed
  desc: Expansive Planner Algorithm with downscaled image for distance.
  code:
  - diffeoplan.library.InformedSearch
  - max_ittr: 250
    thresh: 0.1
    nsteps: 5
    metric: neigh2
        
- id: expansive_3
  desc: Expansive Planner Algorithm with downscaled image for distance.
  code:
  - diffeoplan.library.RandomizedExpansion
  - max_ittr: 250
    thresh: 0.1
    region: 2
    nsteps: 3
    metric: neigh2


- id: graphsearch_breadth_5
  desc: An algorithm that searches all possible sequences of (5 step).
  code:
  - diffeoplan.library.GraphSearchBreadth
  - nsteps: 5
    thresh: 0.1
    metric: neigh2
    
- id: graphsearch_deep_5
  desc: An algorithm that searches all possible sequences of (5 step).
  code:
  - diffeoplan.library.GraphSearchDeep
  - nsteps: 5
    thresh: 0.1
    metric: neigh2
        
- id: expansive_5
  desc: Expansive Planner Algorithm with downscaled image for distance.
  code:
  - diffeoplan.library.RandomizedExpansion
  - max_ittr: 250
    thresh: 0.1
    region: 2
    nsteps: 5
    metric: neigh2
    
- id: expansive_3_r1
  desc: Expansive Planner Algorithm with downscaled image for distance.
  code:
  - diffeoplan.library.RandomizedExpansion
  - max_ittr: 250
    thresh: 0.1
    region: 1
    nsteps: 3
    metric: neigh2
     
- id: expansive_3_r5
  desc: Expansive Planner Algorithm with downscaled image for distance.
  code:
  - diffeoplan.library.RandomizedExpansion
  - max_ittr: 250
    thresh: 0.1
    region: 5
    nsteps: 3
    metric: neigh2    
    

- id: "graphsearch_deep_${n}"
  desc: "Graph search; deep; ${n} steps."
  code:
  - diffeoplan.library.GraphSearchDeep
  - nsteps: "${n}"
    thresh: 0.1
    metric: neigh1eff
