- id: graphsearch
  desc: An algorithm that searches all possible sequences of (3 step).
  code:
  - diffeoplan.library.GraphSearch
  - nsteps: 3
    tresh: 5000
    metric: neigh1

    
- id: expansive
  desc: Expansive planner Algorithm.
  code:
  - diffeoplan.library.RandomizedExpansion
  - max_ittr: 250
    tresh: 5000
    region: 12000
  