
- id: infotree1
  desc: Builds an informed tree
  code:
  - diffeoplan.library.InformedTree
  - hard_choice_params:
        use_isomorphism_heuristics: True
        info_percentile: 50
        info_threshold: null
    diffeo_structure_params:
        tolerance: 0.5 # threshold for two commands to be commutative, etc.
    diffeo_cover_params:
        min_visibility: 0.3  # do not expand nodes with less that this
        info_threshold: 0.5 # threshold for nodes to be the same
        debug_it: 100 # debug graph written every debug_it iterations
        max_it: 1 # maximum number of iterations
        #max_it: 1000 # maximum number of iterations
