- id: random1
  desc: An algorithm that just takes a random guess (1 step).
  code:
  - diffeoplan.library.RandomGuess
  - nsteps: 1

- id: random2
  desc: An algorithm that just takes a random guess (2 steps).
  code:
  - diffeoplan.library.RandomGuess
  - nsteps: 2

- id: graphsearch1
  desc: First graph search algo
  code:
  - diffeoplan.library.GraphSearch
  - alpha: 0