- id: f35s
  desc: Learning by interpolating with fourier transforms (35% displacement)
  code: 
  - learner.DiffeoLearnerRefine
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: fft     
      resolution: [11,11]
      refine_factor: 1.5       
      
- id: f35sfine
  desc: Learning by interpolating with fourier transforms (35% displacement)
  code: 
  - learner.DiffeoLearnerRefine
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: fft 
      resolution: [21,29]
      refine_factor: 1.5           
      
      
- id: fast35s
  desc: Fast refined learning by PIL image interpolation (35% displacement)
  code: 
  - learner.DiffeoLearnerRefineFast
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: fast-bilinear
      resolution: [11,15]
      refine_factor: 1.5
      update_uncertainty: True
      
- id: fast35s-15
  desc: Fast refined learning by PIL image interpolation variable displacement and search grid
  code: 
  - learner.DiffeoLearnerRefineFast
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: fast-bilinear
      resolution: [15, 15]
      refine_factor: 5
      update_uncertainty: False
      info: {'plot_ranges': {'uncertainty_max':25}}
      
- id: fast35s-9
  desc: Fast refined learning by PIL image interpolation variable displacement and search grid
  code: 
  - learner.DiffeoLearnerRefineFast
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: fast-bilinear
      resolution: [9, 9]
      refine_factor: 3
      update_uncertainty: False
      info: {'plot_ranges': {'uncertainty_max':25}}
      
- id: "fast${sa}s-${g}"
  desc: Fast refined learning by PIL image interpolation variable displacement and search grid
  code: 
  - learner.DiffeoLearnerRefineFast
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: ["0.${sa}", "0.${sa}"]
      refine_method: fast-bilinear
      resolution: ["${g}", "${g}"]
      refine_factor: 2.0
      update_uncertainty: False
      info: {'plot_ranges': {'uncertainty_max':25}}
            
#- id: "fast${sa}s-${g}-u"
#  desc: Fast refined learning by PIL image interpolation variable displacement and search grid and improved uncertainty estimation
#  code: 
#  - learner.DiffeoLearnerRefineFast
#  - use_fast: True 
#    diffeo_estimator_params:
#      max_displ: ["0.${sa}", "0.${sa}"]
#      refine_method: fast-bilinear
#      resolution: ["${g}", "${g}"]
#      refine_factor: 1.3
#      update_uncertainty: True
      
- id: fast35s-bc
  desc: Fast refined learning by PIL image interpolation (35% displacement)
  code: 
  - learner.DiffeoLearnerRefineFast
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: fast-bicubic
      resolution: [11,15]
      refine_factor: 1.5
      
      
- id: fasttest
  desc: Fast refined learning by PIL image interpolation (35% displacement)
  code: 
  - learner.DiffeoLearnerRefineFast
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: fast-bilinear
      resolution: [25, 25]
      refine_factor: 1.5

- id: r35s-bl
  desc: Refined learning by PIL image interpolation (35% displacement)
  code: 
  - learner.DiffeoLearnerRefine
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: standard-bilinear
      resolution: [11,11]
      refine_factor: 1.5
      
- id: r35s-bc
  desc: Refined learning by PIL image interpolation (35% displacement)
  code: 
  - learner.DiffeoLearnerRefine
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: standard-bicubic
      resolution: [11,11]
      refine_factor: 1.5
      
- id: r35sfine-bl
  desc: Refined learning by PIL image interpolation (35% displacement)
  code: 
  - learner.DiffeoLearnerRefine
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: standard-bilinear
      resolution: [21,21]
      refine_factor: 1.5
      
- id: r35sfine-bc
  desc: Refined learning by PIL image interpolation (35% displacement)
  code: 
  - learner.DiffeoLearnerRefine
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: standard-bilinear
      resolution: [21,21]
      refine_factor: 1.5

      
- id: ldr35-64-test
  desc: Test learner for landroid rangefinder 64x64 images native resolution
  code:
  - learner.DiffeoLearnerRefineFast
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: fast-bilinear
      resolution: [23,23]
      refine_factor: 1.5
      update_uncertainty: True
            
- id: ldr35-128-test
  desc: Test learner for landroid rangefinder 128x128 images native resolution
  code:
  - learner.DiffeoLearnerRefineFast
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      refine_method: fast-bilinear
      resolution: [45,45]
      refine_factor: 1.5
      update_uncertainty: True