- id: neigh1
  desc: "Neighbor distance for a scaled image (160,120)"
  code:
  - diffeoplan.library.DistanceNeighbor
  - size: [160, 120]
    neighborarea: [4, 4]

- id: neigh1eff
  desc: "More efficient"
  code:
  - diffeoplan.library.DistanceNeighborEff
  - size: [160, 120]
    neighborarea: [4, 4]


- id: neigh2
  desc: Neighbor distance for a scaled image
  code:
  - diffeoplan.library.DistanceNeighbor
  - size: [40, 30]
    neighborarea: [2, 2]
    

- id: neigh2eff
  desc: Neighbor distance for a scaled image
  code:
  - diffeoplan.library.DistanceNeighborEff
  - size: [40, 30]
    neighborarea: [2, 2]
    

- id: L1
  desc: L1 distance
  code:
  - diffeoplan.library.DistanceNorm
  - order: 1


- id: L2
  desc: L2
  code:
  - diffeoplan.library.DistanceNorm
  - order: 2
