# You can use the following symbols
# p = np.array([x,y])
# a := numpy.array
# rotdeg(p, deg)
# dot(a,b)

- id: px1
  desc: "Horizontal translation (left), plane topology"
  code: 
  - diffeoplan.library.EvalDiffeo
  - function: '[x+0.05, y]' 
    inverse:  '[x-0.05, y]'
    topology: plane

- id: tx1
  desc: "Horizontal translation (left), toroidal topology"
  code: 
  - diffeoplan.library.EvalDiffeo
  - function: '[x+0.05, y]' 
    inverse:  '[x-0.05, y]'
    topology: torus

- id: py1
  desc: Vertical translation  (up)
  code: 
  - diffeoplan.library.EvalDiffeo
  - function: '[x, y+0.05]' 
    inverse:  '[x, y-0.05]'
    topology: torus

- id: pr1
  desc: Rotation around the center
  code: 
  - diffeoplan.library.EvalDiffeo
  - function: 'rotdeg(p,+25)' 
    inverse:  'rotdeg(p,-25)' 
    topology: plane

- id: pr2
  desc: Rotation around the corner
  code: 
  - diffeoplan.library.EvalDiffeo
  - function: 'rotdeg(p,+25)' 
    inverse:  'rotdeg(p,-25)' 
    topology: plane


- id: pz1
  desc: Zoom in the middle of the image
  code: 
  - diffeoplan.library.EvalDiffeo
  - function: 'p * 1.1' 
    inverse:  'p / 1.1' 
    topology: plane
 

- id: "I${id_diffeo}"
  desc: "Inverse of ${id_diffeo}"
  code:
  - diffeoplan.library.make_inverse
  - id_diffeo: "${id_diffeo}"

- id: "R2${id_diffeo}"
  desc: "Double application of ${id_diffeo}"
  code:
  - diffeoplan.library.repeat
  - id_diffeo: "${id_diffeo}"
    times: 2

- id: "R3${id_diffeo}"
  desc: "Triple application of ${id_diffeo}"
  code:
  - diffeoplan.library.repeat
  - id_diffeo: "${id_diffeo}"
    times: 3
