- id: neigh1
  desc: "Neighbor distance for a scaled image (160,120)"
  code:
  - diffeoplan.library.DistanceNeighbor
  - size: [160, 120]
    neighborarea: [4, 4]

- id: neigh1eff
  desc: "More efficient"
  code:
  - diffeoplan.library.DistanceNeighborEff
  - size: [160, 120]
    neighborarea: [4, 4]


- id: neigh2
  desc: Neighbor distance for a scaled image
  code:
  - diffeoplan.library.DistanceNeighbor
  - size: [40, 30]
    neighborarea: [2, 2]
    

- id: neigh2eff
  desc: Neighbor distance for a scaled image
  code:
  - diffeoplan.library.DistanceNeighborEff
  - size: [40, 30]
    neighborarea: [2, 2]

- id: "c${distance}"
  desc: "Distance ${distance} on cropped image."
  code:
  - diffeoplan.library.DistanceCrop
  - distance: "${distance}"
    top: 0.25
    left: 0.25
    right: 0.25
    bottom: 0.25



- id: N01
  desc: XXX
  code:
  - diffeoplan.library.DistanceNeighborRatio
  - ratios: [0.01, 0.01]

- id: N10
  desc: XXX
  code:
  - diffeoplan.library.DistanceNeighborRatio
  - ratios: [0.1, 0.1]

- id: N30
  desc: XXX
  code:
  - diffeoplan.library.DistanceNeighborRatio
  - ratios: [0.3, 0.3]

- id: N20
  desc: XXX
  code:
  - diffeoplan.library.DistanceNeighborRatio
  - ratios: [0.2, 0.2]

- id: D05
  desc: XXX
  code:
  - diffeoplan.library.DistanceNeighborDist
  - ratios: [0.05, 0.05]


- id: D10
  desc: XXX
  code:
  - diffeoplan.library.DistanceNeighborDist
  - ratios: [0.1, 0.1]

- id: D20
  desc: XXX
  code:
  - diffeoplan.library.DistanceNeighborDist
  - ratios: [0.2, 0.2]

- id: D30
  desc: XXX
  code:
  - diffeoplan.library.DistanceNeighborDist
  - ratios: [0.3, 0.3]


- id: L1
  desc: L1 distance
  code:
  - diffeoplan.library.DistanceNorm
  - order: 1


- id: L2
  desc: L2
  code:
  - diffeoplan.library.DistanceNorm
  - order: 2

- id: L1w
  desc: "L1, weighted by uncertainty"
  code:
  - diffeoplan.library.DistanceNormWeighted
  - order: 1


- id: L2w
  desc: "L2, weighted by uncertainty"
  code:
  - diffeoplan.library.DistanceNormWeighted
  - order: 2
