- id: n35o
  desc: Normal learner (35% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      inference_method: order

- id: s35s
  desc: State variant learner (35% displacement)
  code: 
  - learner.DiffeoLearnerState
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      inference_method: sim
      
- id: a35s
  desc: Create animation of learning (35% displacement)
  code: 
  - learner.DiffeoLearnerAnimation
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      inference_method: sim
      
- id: s60s
  desc: State variant learner (35% displacement)
  code: 
  - learner.DiffeoLearnerState
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.60, 0.60]
      inference_method: sim

- id: n25o
  desc: Normal learner (25% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.25, 0.25]
      inference_method: order

- id: n20o
  desc: Normal learner (20% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.20, 0.20]
      inference_method: order

- id: n15o
  desc: Normal learner (15% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.15, 0.15]
      inference_method: order

- id: n10o
  desc: Normal learner (10% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.10, 0.10]
      inference_method: order
      
- id: n05o
  desc: Normal learner (5% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.05, 0.05]
      inference_method: order


- id: n35s
  desc: Normal learner (35% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      inference_method: sim
      
- id: p35s
  desc: Probability learner (35% displacement)
  code: 
  - learner.DiffeoLearnerProbability
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      inference_method: sim

- id: c35s
  desc: Continuous Probability learner (35% displacement)
  code: 
  - learner.DiffeoLearnerProbability
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.35, 0.35]
      inference_method: quad

- id: n25s
  desc: Normal learner (25% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.25, 0.25]
      inference_method: sim

- id: n20s
  desc: Normal learner (20% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.20, 0.20]
      inference_method: sim

- id: n15s
  desc: Normal learner (15% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.15, 0.15]
      inference_method: sim

- id: n10s
  desc: Normal learner (10% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.10, 0.10]
      inference_method: sim
      
- id: n05s
  desc: Normal learner (5% displacement)
  code: 
  - learner.DiffeoLearner
  - use_fast: True 
    diffeo_estimator_params:
      max_displ: [0.05, 0.05]
      inference_method: sim
