

- id: "gnbn1_it${n}"
  desc: "GNBN1 := One-dir search; no pre-filtering; no post-filtering; ${n} iterations."
  code:
  - diffeoplan.library.GenericGraphPlanner
  - bidirectional: False
    metric_goal: &metric_goal L2w
    metric_collapse: &metric_collapse L2w
    metric_collapse_threshold: -1 # no collapse
    max_iterations: "${n}"
    max_depth: &max_depth 15
    
- id: "samp_t1_l${n}"
  desc: "Sample based planner for max length ${n}"
  code:
  - diffeoplan.library.SamplePlanner
  - metric_goal: L2
    plan_time: 0.5
    plan_max_length: 5
    
- id: "gnbc1_it${n}"
  desc: "GNBC1 := One-dir search; no pre-filtering; L2w post (0.1); ${n} iterations."
  code:
  - diffeoplan.library.GenericGraphPlanner
  - bidirectional: False
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: &metric_collapse_threshold 0.001
    max_iterations: "${n}"
    max_depth: *max_depth

- id: "gebn1_it${n}"
  desc: "One-dir search; pre-filter equiv; no post-filtering; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlanner
  - bidirectional: False
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: -1 # no collapse
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: &diffeo_structure_params
        tolerance: 0.5 # threshold for two commands to be commutative, etc.
    
- id: "gebc1_it${n}"
  desc: "One-dir search; pre-filter equiv; no post-filtering; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlanner
  - bidirectional: False
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params

- id: "bnbn1_it${n}"
  desc: "Bi-dir search; no pre-filtering; no post-filtering; ${n} iterations."
  code:
  - diffeoplan.library.GenericGraphPlanner
  - bidirectional: True
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: -1 # no collapse
    max_iterations: "${n}"
    max_depth: *max_depth

- id: "bnbc1_it${n}"
  desc: "Bi-dir search; no pre-filtering; L2w post (0.1); ${n} iterations."
  code:
  - diffeoplan.library.GenericGraphPlanner
  - bidirectional: True
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: *metric_collapse_threshold 
    max_iterations: "${n}"
    max_depth: 15


- id: "bebn1_it${n}"
  desc: "Bi-dir search; pre-filter equiv; no post-filtering; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlanner
  - bidirectional: True
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: -1 # no collapse
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params
    
- id: "bebc1_it${n}"
  desc: "Bi-dir search; pre-filter equiv; b-first; L2W collapse; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlanner
  - bidirectional: True
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params

- id: "bngc1_it${n}"
  desc: "BNGC1 := Bi-dir search; greedy; L2W collapse; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlannerGreedy
  - bidirectional: True
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: &no_ds
        tolerance: -1 # threshold for two commands to be commutative, etc.

    metric_attractor: *metric_goal # could choose a different one in principle

- id: "bntc1_it${n}"
  desc: "BNTC1 := Bi-dir search; greedy-tree; L2W collapse; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlannerGreedyTree
  - bidirectional: True
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *no_ds
    metric_attractor: *metric_goal # could choose a different one in principle


- id: "begc1_it${n}"
  desc: "BEGC1 := Bi-dir search; pre-filter equiv; greedy; L2W collapse; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlannerGreedy
  - bidirectional: True
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params
    metric_attractor: *metric_goal # could choose a different one in principle

- id: "betc1_it${n}"
  desc: "BETC1 := Bi-dir search; pre-filter equiv; greedy-tree; L2W collapse; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlannerGreedyTree
  - bidirectional: True
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params
    metric_attractor: *metric_goal # could choose a different one in principle

- id: "betcb1_it${n}"
  desc: "BETCB1 := Bi-dir search; pre-filter equiv; greedy-tree; L2W collapse; ${n} iterations; bracket"
  code:
  - diffeoplan.library.InformedPlannerGreedyTree
  - bidirectional: True
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params
    metric_attractor: *metric_goal # could choose a different one in principle
    pre_expand: ['bracket']

######## Try L2
- id: "betc2_it${n}"
  desc: "Bi-dir search; L2 goal; pre-filter equiv; greedy-tree; L2 collapse; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlannerGreedyTree
  - bidirectional: True
    metric_goal: L2
    metric_collapse: L2
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params
    metric_attractor: *metric_goal # could choose a different one in principle



- id: "begc2_it${n}"
  desc: "Bi-dir search; L2 goal; pre-filter equiv; greedy; L2 collapse; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlannerGreedy
  - bidirectional: True
    metric_goal: L2
    metric_collapse: L2
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params
    metric_attractor: *metric_goal # could choose a different one in principle

- id: "gegc2_it${n}"
  desc: "One-dir search; L2 goal; pre-filter equiv; greedy; L2 collapse; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlannerGreedy
  - bidirectional: False
    metric_goal: L2
    metric_collapse: L2
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params
    metric_attractor: *metric_goal # could choose a different one in principle


- id: "gegn2_it${n}"
  desc: "One-dir search; L2 goal; pre-filter equiv; greedy; no collapse; ${n} iterations."
  code:
  - diffeoplan.library.InformedPlannerGreedy
  - bidirectional: False
    metric_goal: L2
    metric_collapse: L2
    metric_collapse_threshold: -10
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params
    metric_attractor: *metric_goal # could choose a different one in principle

- id: "h1_it${n}"
  desc: "Hierarchical"
  code:
  - diffeoplan.library.InformedPlannerHierarchy
  - bidirectional: False
    metric_goal: *metric_goal
    metric_collapse: *metric_collapse
    metric_collapse_threshold: *metric_collapse_threshold
    max_iterations: "${n}"
    max_depth: *max_depth
    diffeo_structure_params: *diffeo_structure_params
    diffeo_cover_params:
        min_visibility: 0.4  # do not expand nodes with less that this
        info_threshold: 0.5 # threshold for nodes to be the same
        debug_it: 100 # debug graph written every debug_it iterations
        max_it: 1000 # maximum number of iterations
    
# Add some defaults available
# (this helps in defining symbols)
- id: gnbn1_it1000
- id: gnbc1_it1000
- id: bnbn1_it1000
- id: bnbc1_it1000
- id: bebn1_it1000
- id: bebc1_it1000
- id: begc1_it1000
- id: betc1_it1000
- id: gebc1_it1000


