name:                 'logitech_cam'
num_actuators:        2
min_actuator_values:  [-256, -256]
max_actuator_values:  [256, 256]
stop_command:         [0, 0]
ROS_msg_topic:        '/logitech_cam/camera_instr'
frequency:            .25
command_list:         [[0, -256, 0], [-256, 0, 0], [0, 256, 0], [256, 0, 0]]