name:                 'youbot_base1'
num_actuators:        5
min_actuator_values:  [-.1, -.1, -.1, -.1, -.1]
max_actuator_values:  [.1, .1, .1, .1, .1]
stop_command:         [0, 0, 0, 0, 0]
ROS_msg_topic:        '/array2twist/cmd_array'
command_list:         [[+0.15, 0, 0],
                       [-0.15, 0, 0],
                       [0,+0.15, 0],
                       [0,-0.15, 0],
                       [0, 0, +0.075],
                       [0, 0, -0.075]]
home_position:        null
position_topic:       null
