name:                 'youbot_arm'
num_actuators:        5
min_actuator_values:  [-.1, -.1, -.1, -.1, -.1]
max_actuator_values:  [.1, .1, .1, .1, .1]
stop_command:         [0, 0, 0, 0, 0]
ROS_msg_topic:        '/youbot_arm/incremental_instruction'
frequency:            1
home_position:        [3.14, 1, -2.4, 0.2, 3]
position_topic:       '/youbot_arm/position_instruction'
command_list:         [[ .01, 0, 0, 0, 0],
                       [-0.01, 0, 0, 0, 0],
                       [0, 0, .01, 0, ],
                       [0, 0, -0.01, 0, 0]]