name:                 'youbot_arm'
num_actuators:        5
min_actuator_values:  [-.1, -.1, -.1, -.1, -.1]
max_actuator_values:  [.1, .1, .1, .1, .1]
stop_command:         [0, 0, 0, 0, 0]
ROS_msg_topic:        '/youbot_velocity_control'
frequency:            1
#home_position:        [3.14, 1, -2.4, 0.2, 3]
home_position:        [2, .3, -1, 2.5, 3]
position_topic:       '/youbot_arm/position_instruction'
command_list:         [[ .05, 0, 0, 0, 0],
                       [-0.05, 0, 0, 0, 0],
                       [0,  0, 0, .05, 0],
                       [0, 0, 0, -0.05, 0],
                       [0,  0, 0, 0, .25],
                       [0, 0, 0, 0, -0.25]]
                       