"""autogenerated by genpy from camera_actuator/CamCmd.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CamCmd(genpy.Message):
  _md5sum = "46895988c20b47142a93febd21dd1e8a"
  _type = "camera_actuator/CamCmd"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 Pvalue
int64 Tvalue
int64 Zvalue

"""
  __slots__ = ['Pvalue','Tvalue','Zvalue']
  _slot_types = ['int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Pvalue,Tvalue,Zvalue

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CamCmd, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Pvalue is None:
        self.Pvalue = 0
      if self.Tvalue is None:
        self.Tvalue = 0
      if self.Zvalue is None:
        self.Zvalue = 0
    else:
      self.Pvalue = 0
      self.Tvalue = 0
      self.Zvalue = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3q.pack(_x.Pvalue, _x.Tvalue, _x.Zvalue))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.Pvalue, _x.Tvalue, _x.Zvalue,) = _struct_3q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3q.pack(_x.Pvalue, _x.Tvalue, _x.Zvalue))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.Pvalue, _x.Tvalue, _x.Zvalue,) = _struct_3q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3q = struct.Struct("<3q")
