/* Auto-generated by genmsg_cpp for file /home/adam/ros_workspace/surf12adamros/camera_actuator/msg/IntArray.msg */
#ifndef CAMERA_ACTUATOR_MESSAGE_INTARRAY_H
#define CAMERA_ACTUATOR_MESSAGE_INTARRAY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace camera_actuator
{
template <class ContainerAllocator>
struct IntArray_ {
  typedef IntArray_<ContainerAllocator> Type;

  IntArray_()
  : data()
  {
  }

  IntArray_(const ContainerAllocator& _alloc)
  : data(_alloc)
  {
  }

  typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _data_type;
  std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  data;


  typedef boost::shared_ptr< ::camera_actuator::IntArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_actuator::IntArray_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct IntArray
typedef  ::camera_actuator::IntArray_<std::allocator<void> > IntArray;

typedef boost::shared_ptr< ::camera_actuator::IntArray> IntArrayPtr;
typedef boost::shared_ptr< ::camera_actuator::IntArray const> IntArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::camera_actuator::IntArray_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::camera_actuator::IntArray_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace camera_actuator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::camera_actuator::IntArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::camera_actuator::IntArray_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::camera_actuator::IntArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8560fbebb34fa1b9472337b5c3d38fda";
  }

  static const char* value(const  ::camera_actuator::IntArray_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8560fbebb34fa1b9ULL;
  static const uint64_t static_value2 = 0x472337b5c3d38fdaULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_actuator::IntArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "camera_actuator/IntArray";
  }

  static const char* value(const  ::camera_actuator::IntArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::camera_actuator::IntArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16[] data\n\
";
  }

  static const char* value(const  ::camera_actuator::IntArray_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::camera_actuator::IntArray_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct IntArray_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_actuator::IntArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::camera_actuator::IntArray_<ContainerAllocator> & v) 
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CAMERA_ACTUATOR_MESSAGE_INTARRAY_H

